task/urls.py
from django.conf.urls import url,include
from django.contrib import admin
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^timetable/',include('timetable.urls')),
    url(r'^api-auth/',include('rest_framework.urls', namespace='rest_framework')),
]

timetable/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

app_name='timetable'
urlpatterns = [
	url(r'^$',views.timetables.as_view(),name='timetables'),
	url(r'^(?P<pk>[0-9]+)/$',views.result,name='result'),
]

urlpatterns=format_suffix_patterns(urlpatterns)

timetable/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


class timetable(models.Model):
	slot1=models.CharField(max_length=35)
	slot2=models.CharField(max_length=35)
	slot3=models.CharField(max_length=35)
	slot4=models.CharField(max_length=35)
	slot5=models.CharField(max_length=35)

	def __str__(self):
		return 'slot 1- '+self.slot1+'\n'+'slot 2- '+self.slot2+'\n'+'slot 3- '+self.slot3+'\n'+'slot 4- '+self.slot4+'\n'+'slot 5 -'+self.slot5

timetable/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.shortcuts import render,get_object_or_404
from rest_framework import generics
from .serializers import TimetableSerializer
from .models import timetable
from django.http import JsonResponse
# Create your views here.


# def timetable(request):
	# return render(request,'timetable/query.html')


# def result(request,day,slot):
	# return render(request,'timetable/result.html',{
		# 'day': day,
		# 'slot' : slot,
		# })


class timetables(generics.ListCreateAPIView):
	queryset = timetable.objects.all()
	serializer_class = TimetableSerializer

def result(request,pk):
	day1=get_object_or_404(timetable, id = pk)
	serializer = TimetableSerializer(day1)
	return JsonResponse(serializer.data)

timetable/templates/timetable/query.html
<h1>Enter the slot and day to find your class</h1>
<form action="{% url timetable:result  day %}">
	{%  csrf_token %}
	<label>
		<h2>Enter Day</h2>
	</label>
	<input type="number"  name="day"  min="1" max="5" id="day"><br>
	<!--><label>
		<h2>Enter Slot</h2>
	</label>
	<input type="number"  name="slot"  min="1" max="2" id="slot"><br>
	<!-->
	<input type="submit" value="submit">	
</form>

timetable/templates/timetable/result.html
<form action="{% url 'timetable:timetables' %}">
    <label>	
		{% if pk %}
			<center><h2>You have the class of subject {{day}}</h2></center><br>
			<h2>To check  another class Press the Button </h2>
			<input type="submit" value="Check another Class">
		{% else %}
			<h2>Enter the class</h2>
			<input type="submit" value="Check another Class">
		{% endif %}	
    </label>
</form>